data_for_DisplayTypes = [
    'Лобовое табло',
    'Боковое табло',
    'Заднее табло',
    'Салонное табло',
    'Стоп-табло',
    'Медиацентр'
]

data_for_Languages = [
    'Arab',
    'Basque',
    'Bulgarian',
    'Catalan',
    'Chinese',
    'Croatian',
    'Czech',
    'Danish',
    'Deutsch',
    'Dutch',
    'Estonian',
    'Finnish',
    'French',
    'Gal',
    'Greek',
    'Hindi',
    'Hungarian',
    'Irish',
    'Italian',
    'Latvian',
    'Lithuanian',
    'Luxembourgish',
    'Maltese',
    'Polish',
    'Portuguese',
    'Romanian',
    'Scottish Gaelic',
    'Slovak',
    'Slovenian',
    'Spanish',
    'Swedish',
    'Tamil',
    'Turkish',
    'Urdu',
    'Welsh'
]
